AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  pNamePrefix:
    Type: String

  pEnv:
    Type: String

  pMembershipContract:
    Type: String

  pApiDomainRaw:
    Type: String

  pEthHost:
    Type: String

  pCertArn:
    Type: String
    
  pApiDomain:
    Type: String

  pApiStageName:
    Type: String
    Default: svprod

  pLambdaLayer:
    Type: String

  pAdminEmail:
    Type: String

  pBasePathName:
    Description: The url fragment between he end of the domain name and the path specified by AWS::Serverless::Functions
    Default: members
    Type: String

  pVoterGroupToAddressMapJson:
    Type: String

  pMemberEmailDeliveryNotificationEmail:
    Type: String
    

Conditions:
  cFalse: !Equals [ 'true', 'false' ]
  cDev: !Or [ !Equals [ !Ref pNamePrefix, "sv-dev-ba-agm-2019" ], !Equals [ !Ref pEnv, "dev" ] ]


Globals:
  Function:
    Runtime: python3.7
    Timeout: 180
    Environment:
      Variables:
        PYTHON_PATH: "/opt:/opt/deps"
        PYTHONPATH: "/opt:/opt/deps"
        pMembershipContract: !Ref pMembershipContract
        pApiDomainRaw: !Ref pApiDomainRaw
  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
      AllowOrigin: "'*'"
      # AllowOrigin: !Sub "'*.${pApiDomainRaw}'"


Resources:

  rSessionDB:
    Type: AWS::Serverless::SimpleTable
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub ${pNamePrefix}-session-db
      PrimaryKey:
        Name: session_anon_id
        Type: String
      SSESpecification:
        SSEEnabled: true

  rVoterEnrolmentDB:
    Type: AWS::Serverless::SimpleTable
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub ${pNamePrefix}-voter-enrolment-db
      PrimaryKey:
        Name: email_addr
        Type: String
      SSESpecification:
        SSEEnabled: true

  # an admin (service/bot/etc) uses an API key to register a voter's address, weighting, active period, 
  # and logs any arbitrary data needed for later audit
  rFMemberRegister:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${pNamePrefix}-member-registration
      CodeUri: ../app/members
      MemorySize: 1024
      Timeout: 300
      Environment:
        Variables:
          ENV_VAR_TEST: 'uri://test-value'
          pNamePrefix: !Ref pNamePrefix
          pAdminEmail: !Ref pAdminEmail
          pApiDomainRaw: !Ref pApiDomainRaw
          VOTING_ALPHA_TEST_ENV: !If [ cDev, "True", "False" ]
          pVoterGroupToAddressMapJson: !Ref pVoterGroupToAddressMapJson
          pEthHost: !Ref pEthHost
      Handler: api.handlers.message_handler
      Runtime: python3.7
      Layers:
        - !Ref pLambdaLayer
#        - !Ref rMembersLayer
#        - !Ref rCommonLayer
      Events:
        web:
          Type: Api
          Properties:
            Path: /register
            Method: post
            RestApiId: !Ref rMembersOnboardApi
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:PutParameter
              - ssm:DeleteParameter
            Resource:
              - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/sv-${pNamePrefix}-members-api-*
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
            - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/sv-${pNamePrefix}-nodekey-service-*
          - Effect: Allow
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DescribeTable
            Resource:
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${pNamePrefix}-*
          - Effect: Allow
            Action:
              - ses:SendEmail
            Resource:
              - !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${pApiDomainRaw}
              - !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${pApiDomain}
              - !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/*

  rMembersOnboardApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${pNamePrefix}-members-onboard-api
      StageName: !Ref pApiStageName


  rMembersBasePath:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn:
      - rMembersOnboardApiStage  # created via SAM transform
    Properties:
      BasePath: !Ref pBasePathName
      DomainName: !Ref pApiDomain
      Stage: !Ref pApiStageName
      RestApiId: !Ref rMembersOnboardApi

  rMemberEmailDeliverySNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${pNamePrefix}-member-email-deliveries
      Subscription:
        - Endpoint: !Ref pMemberEmailDeliveryNotificationEmail
          Protocol: email
        - Endpoint: !GetAtt rMemberEmailDeliverySQS.Arn
          Protocol: sqs
      TopicName: !Sub ${pNamePrefix}-member-email-deliveries

  rMemberEmailDeliverySQS:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod:  1209600  # 14 days, the maximum
      QueueName: !Sub ${pNamePrefix}-member-email-deliveries


Outputs:
#  oMembersLayer:
#    Value: !Ref rMembersLayer
  oAdminAddMemberFunction:
    Value: !Ref rFMemberRegister
  oMembersOnboardApi:
    Value: !Ref rMembersOnboardApi
  oMembersBasePath:
    Value: !Ref pBasePathName
